name: Central Pages Logic

on:
  workflow_call:
    inputs:
      publish_dir:
        required: false
        default: '.'
        type: string
      runs_on:
        required: false
        default: 'ubuntu-latest'
        type: string

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages-${{ github.repository }}"
  cancel-in-progress: false

jobs:
  deploy-logic:
    runs-on: ${{ inputs.runs_on }}
    permissions:
      contents: write   # Zum Schreiben des Codes
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: 🧹 Pre-Cleanup
        run: rm -rf "${{ github.workspace }}"/* || true

      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure Git Safe Directory
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ inputs.publish_dir }}

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: ✨ Post-Cleanup
        if: always()
        run: |
          rm -rf "${{ github.workspace }}"/*
          docker system prune -f --volumes || true
