name: Central Logic

on:
  workflow_call:
    inputs:
      upstream_url:
        description: 'The URL of the upstream repository'
        required: true
        type: string
      runs_on:
        description: 'Runner label or array'
        required: false
        type: string
        default: 'ubuntu-latest'

jobs:
  run-logic: # Beispiel-Name des Jobs
    runs-on: ${{ inputs.runs_on }}
    # BERECHTIGUNGEN NUR HIER DEFINIEREN
    permissions:
      contents: write
      pull-requests: write # Falls für Automerge benötigt
    if: github.repository != 'lemueIO/.github'
    steps:
      - name: 🧹 Pre-Cleanup
        run: rm -rf ./* ./.git || true

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Sync with Upstream
        run: |
          git remote add upstream "${{ inputs.upstream_url }}" || true
          git fetch upstream main
          git merge upstream/main --no-edit || echo "Kein Merge nötig"
          git push origin main
